# InstantDeath plugin configuration
settings:
  self-kill-requires-permission: false

messages:
  self-kill: "&cYou have died at &eX: %x%&c, &eY: %y%&c, &eZ: %z%"
  target-kill: "&cYou have killed %target% at &eX: %x%&c, &eY: %y%&c, &eZ: %z%"
  player-not-found: "&cPlayer '%target%' not found."
  no-permission: "&cYou do not have permission to kill others."
  usage: "&cUsage: /%label% [player]"
  console-kill: "Player %target% killed from console."
  console-player-not-found: "Player '%target%' not found."
  console-usage: "Usage from console: /%label% <player>"