name: InstantDeath
version: "v2.0.0"
main: my.epic.instantdeath.InstantDeath
commands:
  kill:
    description: Kill yourself or another player (requires permission)
    aliases: [suicide]
    usage: /<command> [player]
permissions:
  instantdeath.kill.self:
    description: Allows player to kill themselves
    default: true
  instantdeath.kill.others:
    description: Allows player to kill others via /kill <player>
    default: op
