name: InstantDeath
version: 'v1.0'
main: my.epic.instantdeath.InstantDeath
api-version: '1.6.1'
authors: [ Emilia ]
description: A simple plugin that lets you kill yourself with /kill without needing any special permissions
website: https://myepicwebsite.net
commands:
  kill:
    description: Kill yourself
    aliases:
      - suicide
    usage: /<command>
folia-supported: true