name: InstantDeath
version: '1'
main: its.felk.instantdeath.InstantDeath
api-version: '1.19'
authors: [ felk ]
description: A simple plugin that lets you kill yourself with /kill without needing any special permissions
website: https://myepicwebsite.net
commands:
  kill:
    description: Kill yourself
    aliases:
      - suicide
    usage: /<command>