name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    - name: Download CraftBukkit 1.6.1 jar
      run: |
        wget -O craftbukkit-1.6.1-R0.1-SNAPSHOT.jar https://myepicwebsite.net/stuff/craftbukkit-1.6.1-R0.1-SNAPSHOT.jar

    - name: Install CraftBukkit jar to local Maven repo
      run: |
        mvn install:install-file \
          -Dfile=craftbukkit-1.6.1-R0.1-SNAPSHOT.jar \
          -DgroupId=org.bukkit \
          -DartifactId=craftbukkit \
          -Dversion=1.6.1-R0.1-SNAPSHOT \
          -Dpackaging=jar

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload built jar
      uses: actions/upload-artifact@v4
      with:
        name: InstantDeath
        path: target/InstantDeath-*.jar

    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
